/*
* Challenge:
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
* By starting with 1 and 2, the first 10 terms will be:
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* By considering the terms in the Fibonacci sequence whose values do not exceed four million,
* find the sum of the even-valued terms.
*/

/**
 * @author Verric
 */


public class Project_2 {

    public static void main(String[] args) {
        long f1 =0;
        long f2 =1;
        long f3 =0;
        long accum =0;
        System.out.println("Starting...");
        
        while(f3 < 4000000){
            
            f1=f2;
            f2=f3;
            f3 =f1+f2;
            
            if (f3%2 == 0){
               accum+=f3;
            }
            
        }System.out.println(accum);
        
    }
    
}
